name: fluttertestapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  responsive_builder: ^0.7.0
  google_fonts: ^5.1.0
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
